const texts = {
  en: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Menu',
    menuHome: 'Home',
    menuAbout: 'About me',
    menuSkills: 'Skills',
    menuProjects: 'Projects',
    menuContacts: 'Contacts',
    langMenu: 'Language',
    mainTitle: 'Welcome!',
    mainText: "This is my personal website. Here you can learn about me, my skills, and explore my projects. Use the menu to navigate between sections, swipe left/right on mobile or use the side menu on desktop. Switch language or theme using the buttons in the top right corner.",
    aboutTitle: 'About me',
    aboutText: "I'm Serhii Hordiichuk, a Full Stack Developer and Cybersecurity Specialist. I have experience in OSINT, AI solutions, and building secure, scalable web applications.",
    skillsTitle: 'Skills',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersecurity (OWASP, pentesting, threat modeling)",
      "OSINT (Open Source Intelligence)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API Design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Cloud: AWS, Azure, GCP",
      "DevOps basics"
    ],
    projectsTitle: 'Projects',
    contactsTitle: 'Contacts',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europe",
      asia: "Asia",
      middleEast: "Middle East",
      india: "India"
    }
  },
  uk: {
    siteTitle: 'Сергій Гордійчук',
    menu: 'Меню',
    menuHome: 'Головна',
    menuAbout: 'Про мене',
    menuSkills: 'Навички',
    menuProjects: 'Проекти',
    menuContacts: 'Контакти',
    langMenu: 'Мова',
    mainTitle: 'Вітаю!',
    mainText: "Це мій персональний сайт. Тут ви знайдете інформацію про мене, мої навички та зможете переглянути мої проекти. Використовуйте меню для переходу між розділами, свайпайте вліво/вправо на мобільному або користуйтеся бічним меню на комп’ютері. Перемикайте мову чи тему за допомогою кнопок у правому верхньому куті.",
    aboutTitle: 'Про мене',
    aboutText: "Я Сергій Гордійчук — Full Stack розробник і спеціаліст з кібербезпеки. Маю досвід у OSINT, розробці AI-рішень та створенні безпечних, масштабованих веб-додатків.",
    skillsTitle: 'Навички',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Кібербезпека (OWASP, пентестинг, моделювання загроз)",
      "OSINT (розвідка з відкритих джерел)",
      "AI та ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API дизайн (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Хмари: AWS, Azure, GCP",
      "Основи DevOps"
    ],
    projectsTitle: 'Проекти',
    contactsTitle: 'Контакти',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Європа",
      asia: "Азія",
      middleEast: "Близький Схід",
      india: "Індія"
    }
  },
  fr: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Menu',
    menuHome: 'Accueil',
    menuAbout: 'À propos',
    menuSkills: 'Compétences',
    menuProjects: 'Projets',
    menuContacts: 'Contacts',
    langMenu: 'Langue',
    mainTitle: 'Bienvenue !',
    mainText: "Ceci est mon site personnel. Vous pouvez en apprendre plus sur moi, mes compétences et découvrir mes projets. Utilisez le menu pour naviguer, faites glisser à gauche/droite sur mobile ou utilisez le menu latéral sur ordinateur. Changez la langue ou le thème en haut à droite.",
    aboutTitle: 'À propos',
    aboutText: "Je suis Serhii Hordiichuk, développeur Full Stack et spécialiste en cybersécurité. J'ai de l'expérience en OSINT, solutions IA et développement d'applications web sécurisées et évolutives.",
    skillsTitle: 'Compétences',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersécurité (OWASP, pentesting, modélisation des menaces)",
      "OSINT (renseignement open source)",
      "IA & ML : Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "Conception d'API (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Cloud : AWS, Azure, GCP",
      "Bases DevOps"
    ],
    projectsTitle: 'Projets',
    contactsTitle: 'Contacts',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europe",
      asia: "Asie",
      middleEast: "Moyen-Orient",
      india: "Inde"
    }
  },
  de: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Menü',
    menuHome: 'Startseite',
    menuAbout: 'Über mich',
    menuSkills: 'Fähigkeiten',
    menuProjects: 'Projekte',
    menuContacts: 'Kontakte',
    langMenu: 'Sprache',
    mainTitle: 'Willkommen!',
    mainText: "Dies ist meine persönliche Website. Hier erfahren Sie mehr über mich, meine Fähigkeiten und meine Projekte. Nutzen Sie das Menü zur Navigation, wischen Sie auf dem Handy oder nutzen Sie das Seitenmenü am Desktop. Sprache oder Thema oben rechts wechseln.",
    aboutTitle: 'Über mich',
    aboutText: "Ich bin Serhii Hordiichuk, Full Stack Entwickler und Cybersecurity-Spezialist. Erfahrung in OSINT, KI-Lösungen und Entwicklung sicherer, skalierbarer Webanwendungen.",
    skillsTitle: 'Fähigkeiten',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersicherheit (OWASP, Pentesting, Bedrohungsmodellierung)",
      "OSINT (Open Source Intelligence)",
      "KI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-Design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Cloud: AWS, Azure, GCP",
      "DevOps Grundlagen"
    ],
    projectsTitle: 'Projekte',
    contactsTitle: 'Kontakte',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europa",
      asia: "Asien",
      middleEast: "Naher Osten",
      india: "Indien"
    }
  },
  es: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Menú',
    menuHome: 'Inicio',
    menuAbout: 'Sobre mí',
    menuSkills: 'Habilidades',
    menuProjects: 'Proyectos',
    menuContacts: 'Contactos',
    langMenu: 'Idioma',
    mainTitle: '¡Bienvenido!',
    mainText: "Este es mi sitio web personal. Aquí puedes saber más sobre mí, mis habilidades y mis proyectos. Usa el menú para navegar, desliza a la izquierda/derecha en móvil o usa el menú lateral en escritorio. Cambia idioma o tema arriba a la derecha.",
    aboutTitle: 'Sobre mí',
    aboutText: "Soy Serhii Hordiichuk, desarrollador Full Stack y especialista en ciberseguridad. Experiencia en OSINT, IA y desarrollo de aplicaciones web seguras y escalables.",
    skillsTitle: 'Habilidades',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Ciberseguridad (OWASP, pentesting, modelado de amenazas)",
      "OSINT (Open Source Intelligence)",
      "IA & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "Diseño de API (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Cloud: AWS, Azure, GCP",
      "Bases de DevOps"
    ],
    projectsTitle: 'Proyectos',
    contactsTitle: 'Contactos',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europa",
      asia: "Asia",
      middleEast: "Medio Oriente",
      india: "India"
    }
  },
  ru: {
    siteTitle: 'Сергей Гордейчук',
    menu: 'Меню',
    menuHome: 'Главная',
    menuAbout: 'Обо мне',
    menuSkills: 'Навыки',
    menuProjects: 'Проекты',
    menuContacts: 'Контакты',
    langMenu: 'Язык',
    mainTitle: 'Добро пожаловать!',
    mainText: "Это мой персональный сайт. Здесь вы найдете информацию обо мне, моих навыках и проектах. Используйте меню для навигации, свайпайте влево/вправо на мобильном или используйте боковое меню на компьютере. Переключайте язык или тему в правом верхнем углу.",
    aboutTitle: 'Обо мне',
    aboutText: "Я Сергей Гордейчук — Full Stack разработчик и специалист по кибербезопасности. Опыт в OSINT, AI-решениях и разработке защищённых, масштабируемых веб-приложений.",
    skillsTitle: 'Навыки',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Кибербезопасность (OWASP, пентестинг, моделирование угроз)",
      "OSINT (разведка по открытым источникам)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "Проектирование API (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Облако: AWS, Azure, GCP",
      "Основы DevOps"
    ],
    projectsTitle: 'Проекты',
    contactsTitle: 'Контакты',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Европа",
      asia: "Азия",
      middleEast: "Ближний Восток",
      india: "Индия"
    }
  },
  ar: {
    siteTitle: 'سيرهي هورديتشوك',
    menu: 'القائمة',
    menuHome: 'الرئيسية',
    menuAbout: 'عنّي',
    menuSkills: 'المهارات',
    menuProjects: 'المشاريع',
    menuContacts: 'تواصل',
    langMenu: 'اللغة',
    mainTitle: 'مرحبًا!',
    mainText: "هذا موقعي الشخصي. هنا يمكنك معرفة المزيد عني ومهاراتي ومشاريعي. استخدم القائمة للتنقل، اسحب لليسار/اليمين على الجوال أو استخدم القائمة الجانبية على الكمبيوتر. غيّر اللغة أو النمط من الزاوية اليمنى العليا.",
    aboutTitle: 'عنّي',
    aboutText: "أنا سيرهي هورديتشوك، مطور Full Stack ومتخصص في الأمن السيبراني. لدي خبرة في OSINT وحلول الذكاء الاصطناعي وتطوير تطبيقات الويب الآمنة والقابلة للتوسع.",
    skillsTitle: 'المهارات',
    skillsList: [
      "JavaScript (ES6+)، TypeScript",
      "Python",
      "Node.js، Express.js",
      "React، Redux، Next.js",
      "HTML5، CSS3، SASS، Bootstrap",
      "SQL (PostgreSQL، MySQL)، MongoDB",
      "Docker، CI/CD، Linux",
      "الأمن السيبراني (OWASP، اختبار الاختراق، نمذجة التهديدات)",
      "OSINT (استخبارات المصادر المفتوحة)",
      "الذكاء الاصطناعي والتعلم الآلي: Prompt Engineering، LLMs، ChatGPT API، TensorFlow، PyTorch",
      "تصميم API (REST، GraphQL)",
      "Git، GitHub، GitLab",
      "السحابة: AWS، Azure، GCP",
      "أساسيات DevOps"
    ],
    projectsTitle: 'المشاريع',
    contactsTitle: 'تواصل',
    contactsText: '',
    footer: '',
    regions: {
      europe: "أوروبا",
      asia: "آسيا",
      middleEast: "الشرق الأوسط",
      india: "الهند"
    }
  },
  hi: {
    siteTitle: 'सर्गी होर्डीचुक',
    menu: 'मेनू',
    menuHome: 'मुखपृष्ठ',
    menuAbout: 'मेरे बारे में',
    menuSkills: 'कौशल',
    menuProjects: 'प्रोजेक्ट्स',
    menuContacts: 'संपर्क',
    langMenu: 'भाषा',
    mainTitle: 'स्वागत है!',
    mainText: "यह मेरी व्यक्तिगत वेबसाइट है। यहाँ आप मेरे बारे में, मेरे कौशल और मेरे प्रोजेक्ट्स के बारे में जान सकते हैं। मेनू का उपयोग करें, मोबाइल पर बाएँ/दाएँ स्वाइप करें या डेस्कटॉप पर साइड मेनू का उपयोग करें। ऊपर दाएँ कोने में भाषा या थीम बदलें।",
    aboutTitle: 'मेरे बारे में',
    aboutText: "मैं सर्गी होर्डीचुक हूँ — फुल स्टैक डेवलपर और साइबर सुरक्षा विशेषज्ञ। OSINT, AI समाधान और सुरक्षित, स्केलेबल वेब एप्लिकेशन बनाने का अनुभव।",
    skillsTitle: 'कौशल',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "साइबर सुरक्षा (OWASP, पेंटेस्टिंग, थ्रेट मॉडलिंग)",
      "OSINT (ओपन सोर्स इंटेलिजेंस)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API डिज़ाइन (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "क्लाउड: AWS, Azure, GCP",
      "DevOps मूल बातें"
    ],
    projectsTitle: 'प्रोजेक्ट्स',
    contactsTitle: 'संपर्क',
    contactsText: '',
    footer: '',
    regions: {
      europe: "यूरोप",
      asia: "एशिया",
      middleEast: "मध्य पूर्व",
      india: "भारत"
    }
  },
  zh: {
    siteTitle: '谢尔盖·霍尔迪丘克',
    menu: '菜单',
    menuHome: '主页',
    menuAbout: '关于我',
    menuSkills: '技能',
    menuProjects: '项目',
    menuContacts: '联系',
    langMenu: '语言',
    mainTitle: '欢迎！',
    mainText: "这是我的个人网站。你可以了解我、我的技能和项目。使用菜单导航，在手机上左右滑动，或在桌面上使用侧边菜单。右上角切换语言或主题。",
    aboutTitle: '关于我',
    aboutText: "我是谢尔盖·霍尔迪丘克，全栈开发者和网络安全专家。拥有OSINT、AI解决方案和安全可扩展Web应用开发经验。",
    skillsTitle: '技能',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "网络安全 (OWASP, 渗透测试, 威胁建模)",
      "OSINT (开源情报)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API设计 (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "云: AWS, Azure, GCP",
      "DevOps基础"
    ],
    projectsTitle: '项目',
    contactsTitle: '联系',
    contactsText: '',
    footer: '',
    regions: {
      europe: "欧洲",
      asia: "亚洲",
      middleEast: "中东",
      india: "印度"
    }
  },
  no: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Meny',
    menuHome: 'Hjem',
    menuAbout: 'Om meg',
    menuSkills: 'Ferdigheter',
    menuProjects: 'Prosjekter',
    menuContacts: 'Kontakt',
    langMenu: 'Språk',
    mainTitle: 'Velkommen!',
    mainText: "Dette er min personlige nettside. Her kan du lære om meg, mine ferdigheter og prosjekter. Bruk menyen for å navigere, sveip til venstre/høyre på mobil eller bruk sidemenyen på PC. Bytt språk eller tema øverst til høyre.",
    aboutTitle: 'Om meg',
    aboutText: "Jeg er Serhii Hordiichuk, fullstack-utvikler og cybersikkerhetsspesialist. Erfaring med OSINT, AI-løsninger og utvikling av sikre, skalerbare webapplikasjoner.",
    skillsTitle: 'Ferdigheter',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersikkerhet (OWASP, pentesting, trusselmodellering)",
      "OSINT (åpen kilde etterretning)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Sky: AWS, Azure, GCP",
      "DevOps-grunnleggende"
    ],
    projectsTitle: 'Prosjekter',
    contactsTitle: 'Kontakt',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europa",
      asia: "Asia",
      middleEast: "Midtøsten",
      india: "India"
    }
  },
  sv: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Meny',
    menuHome: 'Hem',
    menuAbout: 'Om mig',
    menuSkills: 'Färdigheter',
    menuProjects: 'Projekt',
    menuContacts: 'Kontakt',
    langMenu: 'Språk',
    mainTitle: 'Välkommen!',
    mainText: "Detta är min personliga webbplats. Här kan du läsa om mig, mina färdigheter och mina projekt. Använd menyn för att navigera, svep vänster/höger på mobil eller använd sidomenyn på dator. Byt språk eller tema uppe till höger.",
    aboutTitle: 'Om mig',
    aboutText: "Jag är Serhii Hordiichuk, fullstackutvecklare och cybersäkerhetsspecialist. Erfarenhet av OSINT, AI-lösningar och utveckling av säkra, skalbara webbapplikationer.",
    skillsTitle: 'Färdigheter',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersäkerhet (OWASP, pentesting, hotmodellering)",
      "OSINT (öppen källkod underrättelse)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Moln: AWS, Azure, GCP",
      "DevOps-grunder"
    ],
    projectsTitle: 'Projekt',
    contactsTitle: 'Kontakt',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europa",
      asia: "Asien",
      middleEast: "Mellanöstern",
      india: "Indien"
    }
  },
  da: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Menu',
    menuHome: 'Hjem',
    menuAbout: 'Om mig',
    menuSkills: 'Færdigheder',
    menuProjects: 'Projekter',
    menuContacts: 'Kontakt',
    langMenu: 'Sprog',
    mainTitle: 'Velkommen!',
    mainText: "Dette er min personlige hjemmeside. Her kan du lære om mig, mine færdigheder og projekter. Brug menuen til at navigere, swipe venstre/højre på mobilen eller brug sidemenuen på desktop. Skift sprog eller tema øverst til højre.",
    aboutTitle: 'Om mig',
    aboutText: "Jeg er Serhii Hordiichuk, fullstack-udvikler og cybersikkerhedsspecialist. Erfaring med OSINT, AI-løsninger og udvikling af sikre, skalerbare webapplikationer.",
    skillsTitle: 'Færdigheder',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Cybersikkerhed (OWASP, pentesting, trusselsmodellering)",
      "OSINT (åben kilde efterretning)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Cloud: AWS, Azure, GCP",
      "DevOps-grundlæggende"
    ],
    projectsTitle: 'Projekter',
    contactsTitle: 'Kontakt',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Europa",
      asia: "Asien",
      middleEast: "Mellemøsten",
      india: "Indien"
    }
  },
  is: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Valmynd',
    menuHome: 'Heim',
    menuAbout: 'Um mig',
    menuSkills: 'Hæfni',
    menuProjects: 'Verkefni',
    menuContacts: 'Samskipti',
    langMenu: 'Tungumál',
    mainTitle: 'Velkomin!',
    mainText: "Þetta er mín persónulega vefsíða. Hér getur þú kynnt þér mig, hæfni mína og verkefni. Notaðu valmyndina til að vafra, strjúktu til vinstri/hægri á farsíma eða notaðu hliðarvalmynd á tölvu. Skiptu um tungumál eða þema efst til hægri.",
    aboutTitle: 'Um mig',
    aboutText: "Ég er Serhii Hordiichuk, fullstack forritari og netöryggissérfræðingur. Reynsla af OSINT, gervigreindarlausnum og öruggum, stigstærum veflausnum.",
    skillsTitle: 'Hæfni',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Netöryggi (OWASP, pentesting, ógnamódel)",
      "OSINT (upplýsingar úr opnum gögnum)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-hönnun (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Ský: AWS, Azure, GCP",
      "DevOps-grunnur"
    ],
    projectsTitle: 'Verkefni',
    contactsTitle: 'Samskipti',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Evrópa",
      asia: "Asía",
      middleEast: "Miðausturlönd",
      india: "Indland"
    }
  },
  fo: {
    siteTitle: 'Serhii Hordiichuk',
    menu: 'Valmynd',
    menuHome: 'Heim',
    menuAbout: 'Um meg',
    menuSkills: 'Førleikar',
    menuProjects: 'Verkætlanir',
    menuContacts: 'Samband',
    langMenu: 'Mál',
    mainTitle: 'Vælkomin!',
    mainText: "Hetta er mín persónliga heimasíða. Her kanst tú lesa um meg, mínar førleikar og verkætlanir. Brúka valmyndina at navigera, sveip vinstru/høgru á fartelefon ella brúka síðumenyu á teldu. Skift mál ella tema ovast til høgru.",
    aboutTitle: 'Um meg',
    aboutText: "Eg eri Serhii Hordiichuk, fullstack menari og nettrygdarserfrøðingur. Royndir við OSINT, AI-loysnum og menning av tryggum, skalanligum vevforritum.",
    skillsTitle: 'Førleikar',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "Nettrygd (OWASP, pentesting, hóttaframleiðsla)",
      "OSINT (opin keldu greining)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API-design (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "Ský: AWS, Azure, GCP",
      "DevOps-grundarlag"
    ],
    projectsTitle: 'Verkætlanir',
    contactsTitle: 'Samband',
    contactsText: '',
    footer: '',
    regions: {
      europe: "Evrópa",
      asia: "Asía",
      middleEast: "Miðeystri",
      india: "India"
    }
  },
  ko: {
    siteTitle: '세르히 호르디추크',
    menu: '메뉴',
    menuHome: '홈',
    menuAbout: '소개',
    menuSkills: '기술',
    menuProjects: '프로젝트',
    menuContacts: '연락처',
    langMenu: '언어',
    mainTitle: '환영합니다!',
    mainText: "이곳은 저의 개인 웹사이트입니다. 저와 제 기술, 프로젝트를 알아보세요. 메뉴로 이동하거나, 모바일에서 좌우로 스와이프하거나, 데스크톱에서 사이드 메뉴를 사용하세요. 오른쪽 위에서 언어나 테마를 변경할 수 있습니다.",
    aboutTitle: '소개',
    aboutText: "저는 세르히 호르디추크입니다. 풀스택 개발자이자 사이버 보안 전문가입니다. OSINT, AI 솔루션, 안전하고 확장 가능한 웹 애플리케이션 구축 경험이 있습니다.",
    skillsTitle: '기술',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "사이버 보안 (OWASP, 모의 해킹, 위협 모델링)",
      "OSINT (오픈 소스 인텔리전스)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API 설계 (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "클라우드: AWS, Azure, GCP",
      "DevOps 기초"
    ],
    projectsTitle: '프로젝트',
    contactsTitle: '연락처',
    contactsText: '',
    footer: '',
    regions: {
      europe: "유럽",
      asia: "아시아",
      middleEast: "중동",
      india: "인도"
    }
  },
  ja: {
    siteTitle: 'セルヒー・ホルディーチュク',
    menu: 'メニュー',
    menuHome: 'ホーム',
    menuAbout: '自己紹介',
    menuSkills: 'スキル',
    menuProjects: 'プロジェクト',
    menuContacts: '連絡先',
    langMenu: '言語',
    mainTitle: 'ようこそ！',
    mainText: "これは私の個人ウェブサイトです。私や私のスキル、プロジェクトについてご覧いただけます。メニューで移動し、モバイルでは左右にスワイプ、デスクトップではサイドメニューを使ってください。右上のボタンで言語やテーマを変更できます。",
    aboutTitle: '自己紹介',
    aboutText: "私はセルヒー・ホルディーチュクです。フルスタック開発者でサイバーセキュリティの専門家です。OSINT、AIソリューション、安全でスケーラブルなWebアプリ開発の経験があります。",
    skillsTitle: 'スキル',
    skillsList: [
      "JavaScript (ES6+), TypeScript",
      "Python",
      "Node.js, Express.js",
      "React, Redux, Next.js",
      "HTML5, CSS3, SASS, Bootstrap",
      "SQL (PostgreSQL, MySQL), MongoDB",
      "Docker, CI/CD, Linux",
      "サイバーセキュリティ (OWASP, ペネトレーションテスト, 脅威モデリング)",
      "OSINT (オープンソースインテリジェンス)",
      "AI & ML: Prompt Engineering, LLMs, ChatGPT API, TensorFlow, PyTorch",
      "API設計 (REST, GraphQL)",
      "Git, GitHub, GitLab",
      "クラウド: AWS, Azure, GCP",
      "DevOps基礎"
    ],
    projectsTitle: 'プロジェクト',
    contactsTitle: '連絡先',
    contactsText: '',
    footer: '',
    regions: {
      europe: "ヨーロッパ",
      asia: "アジア",
      middleEast: "中東",
      india: "インド"
    }
  }
};
