backend:
  name: github
  repo: serhii-hordiichuk.github.io/Portfolio/
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "translations"
    label: "Переклади"
    files:
      - label: "Мовні рядки"
        name: "lang"
        file: "js/lang.js"
        fields:
          - { label: "JS-код з перекладами", name: "body", widget: "code", default_language: "javascript" }

  - name: "projects"
    label: "Проєкти"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    extension: "html"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "HTML-код", name: "body", widget: "code", default_language: "html" }
